### ISSUE TITLE
Dev command should run build script instead of transpiling data sources

### ISSUE THREAD

**Issue by jlengstorf** [gramps-graphql/data-source-base#16]

**Comment by kbrandwijk** [comment]
Should probably go here: https://github.com/gramps-graphql/gramps-cli?

**Comment by jlengstorf** [comment]
Issue moved to [gramps-graphql/gramps-cli #32](https://github.com/gramps-graphql/gramps-cli/issues/32) via [**ZenHub**](https://www.zenhub.com/)
