### ISSUE TITLE
Include schema file in build output

### ISSUE THREAD

**Issue by kbrandwijk** [gramps-graphql/data-source-base#17]
Currently, the schema file is read in the index file, and injected by babel. The `.graphql` file itself is not included in the build. In order to generate compile-time bindings when using a datasource, the schema file itself is needed. Can this be included in the build output by default?

**Comment by jlengstorf** [comment]
That should be simple enough; we'd just need to add `cpy-cli` and add a step to the package.json build process to copy `.graphql` files.

This would be a great first contribution for someone. _hint hint wink nudge nudge_ 😄

**Comment by kbrandwijk** [comment]
Or second...

**Comment by jlengstorf** [comment]
I wasn't talking about you, @kbrandwijk. :)

**Comment by kbrandwijk** [comment]
Oops ^^ Aaaand... it's done...
